apply plugin: 'com.android.library'

android {
    namespace "com.github.barteksc.pdfviewer"
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        versionCode 1
        versionName "3.4.0"
    }

    ndkVersion "28.0.13004108"

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = false
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.7.0'
    api 'com.github.mhiew:pdfium-android:1.9.2'
}
